
[jetson]
10.111.14.161 ansible_user=jetson ansible_password=jetson
10.111.14.162 ansible_user=jetson ansible_password=jetson

[jetson:vars]
# Tell Ansible to use system Python 3
ansible_python_interpreter=/usr/bin/python3
ansible_password=jetson
ansible_become_pass=jetson
